/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/

import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery } from '@tanstack/react-query'
import { ExternalLink, ImageIcon, LoaderCircle, Sparkles } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useForm } from 'react-hook-form'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import { z } from 'zod'

import { Main } from '@/components/layout'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  Form,
  FormControl,
  FormDescription,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { NativeSelect, NativeSelectOption } from '@/components/ui/native-select'
import { Textarea } from '@/components/ui/textarea'

import {
  createImage,
  getImageModels,
  type GeneratedImage,
  type ImageGenerationRequest,
} from './api'

const imageFormSchema = z.object({
  model: z.string().trim().min(1, 'Model is required'),
  prompt: z.string().trim().min(1, 'Prompt is required').max(32000),
  n: z.number().int().min(1).max(4),
  size: z.string(),
  quality: z.string(),
})

type ImageFormValues = z.infer<typeof imageFormSchema>

function getImageSource(image: GeneratedImage): string {
  if (image.url) return image.url
  if (image.b64_json) return `data:image/png;base64,${image.b64_json}`
  return ''
}

export function ImageGeneration() {
  const { t } = useTranslation()
  const [images, setImages] = useState<GeneratedImage[]>([])

  const form = useForm<ImageFormValues>({
    resolver: zodResolver(imageFormSchema),
    defaultValues: {
      model: '',
      prompt: '',
      n: 1,
      size: 'auto',
      quality: 'auto',
    },
  })

  const modelsQuery = useQuery({
    queryKey: ['image-generation-models'],
    queryFn: getImageModels,
    retry: false,
  })
  let modelDescription = t(
    'No available image models are configured in Channels'
  )
  if (modelsQuery.isLoading) {
    modelDescription = t('Loading models from Channels')
  } else if (modelsQuery.data?.length) {
    modelDescription = t('{{count}} available image models', {
      count: modelsQuery.data.length,
    })
  }

  useEffect(() => {
    const firstModel = modelsQuery.data?.[0]
    if (!firstModel) return
    const currentModel = form.getValues('model')
    if (!modelsQuery.data?.includes(currentModel)) {
      form.setValue('model', firstModel)
    }
  }, [form, modelsQuery.data])

  const createMutation = useMutation({
    mutationFn: createImage,
    onSuccess: (response) => {
      setImages(response.data ?? [])
      toast.success(t('Image generated successfully'))
    },
  })

  const onSubmit = (values: ImageFormValues) => {
    const request: ImageGenerationRequest = {
      model: values.model.trim(),
      prompt: values.prompt.trim(),
      n: values.n,
      response_format: 'url',
    }
    if (values.size !== 'auto') request.size = values.size
    if (values.quality !== 'auto') request.quality = values.quality
    createMutation.mutate(request)
  }

  return (
    <Main className='space-y-6 overflow-x-hidden overflow-y-auto px-3 py-6 pb-12 sm:px-4'>
      <div>
        <h1 className='flex items-center gap-2 text-2xl font-semibold'>
          <ImageIcon className='size-6' />
          {t('Image Generation')}
        </h1>
        <p className='text-muted-foreground mt-1 text-sm'>
          {t('Generate images with configured image models')}
        </p>
      </div>

      <div className='grid gap-6 xl:grid-cols-[minmax(0,5fr)_minmax(360px,4fr)]'>
        <Card>
          <CardHeader>
            <CardTitle>{t('Generation settings')}</CardTitle>
            <CardDescription>
              {t('Images are generated by your configured upstream channels')}
            </CardDescription>
          </CardHeader>
          <CardContent>
            <Form {...form}>
              <form
                className='space-y-5'
                onSubmit={form.handleSubmit(onSubmit)}
              >
                <FormField
                  control={form.control}
                  name='model'
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('Model')}</FormLabel>
                      <FormControl>
                        <NativeSelect
                          className='w-full'
                          disabled={
                            modelsQuery.isLoading ||
                            (modelsQuery.data?.length ?? 0) === 0
                          }
                          value={field.value}
                          onChange={field.onChange}
                        >
                          {(modelsQuery.data ?? []).map((model) => (
                            <NativeSelectOption key={model} value={model}>
                              {model}
                            </NativeSelectOption>
                          ))}
                        </NativeSelect>
                      </FormControl>
                      <FormDescription>{modelDescription}</FormDescription>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name='prompt'
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>{t('Prompt')}</FormLabel>
                      <FormControl>
                        <Textarea
                          {...field}
                          className='min-h-40 resize-y'
                          placeholder={t(
                            'Describe the image, composition, lighting, and style'
                          )}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <div className='grid gap-4 md:grid-cols-3'>
                  <FormField
                    control={form.control}
                    name='size'
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('Size')}</FormLabel>
                        <FormControl>
                          <NativeSelect
                            className='w-full'
                            value={field.value}
                            onChange={field.onChange}
                          >
                            {[
                              'auto',
                              '1024x1024',
                              '1024x1536',
                              '1536x1024',
                              '1024x1792',
                              '1792x1024',
                              '512x512',
                            ].map((size) => (
                              <NativeSelectOption key={size} value={size}>
                                {size === 'auto' ? t('Automatic') : size}
                              </NativeSelectOption>
                            ))}
                          </NativeSelect>
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name='quality'
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('Quality')}</FormLabel>
                        <FormControl>
                          <NativeSelect
                            className='w-full'
                            value={field.value}
                            onChange={field.onChange}
                          >
                            {[
                              'auto',
                              'standard',
                              'hd',
                              'low',
                              'medium',
                              'high',
                            ].map((quality) => (
                              <NativeSelectOption key={quality} value={quality}>
                                {t(quality)}
                              </NativeSelectOption>
                            ))}
                          </NativeSelect>
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name='n'
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>{t('Image count')}</FormLabel>
                        <FormControl>
                          <Input
                            type='number'
                            min={1}
                            max={4}
                            value={field.value}
                            onChange={(event) =>
                              field.onChange(event.target.valueAsNumber)
                            }
                          />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <Alert>
                  <Sparkles />
                  <AlertTitle>{t('Lightweight relay')}</AlertTitle>
                  <AlertDescription>
                    {t(
                      'Generated images are returned directly from the upstream and are not stored on this server'
                    )}
                  </AlertDescription>
                </Alert>

                <Button
                  className='w-full'
                  type='submit'
                  disabled={
                    createMutation.isPending ||
                    (modelsQuery.data?.length ?? 0) === 0
                  }
                >
                  {createMutation.isPending ? (
                    <LoaderCircle className='animate-spin' />
                  ) : (
                    <Sparkles />
                  )}
                  {t('Generate image')}
                </Button>
              </form>
            </Form>
          </CardContent>
        </Card>

        <Card className='min-h-96'>
          <CardHeader>
            <CardTitle>{t('Generated images')}</CardTitle>
            <CardDescription>
              {t('Results from the latest request appear here')}
            </CardDescription>
          </CardHeader>
          <CardContent>
            {images.length === 0 ? (
              <div className='text-muted-foreground flex min-h-72 flex-col items-center justify-center gap-3 text-center'>
                <ImageIcon className='size-12 opacity-40' />
                <p>{t('Submit a request to see generated images here')}</p>
              </div>
            ) : (
              <div className='grid gap-4 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2'>
                {images.map((image) => {
                  const source = getImageSource(image)
                  return (
                    <div
                      key={source || image.revised_prompt || 'generated-image'}
                      className='space-y-3 rounded-lg border p-3'
                    >
                      {source ? (
                        <img
                          className='bg-muted aspect-square w-full rounded-md object-contain'
                          src={source}
                          alt={image.revised_prompt || t('Generated image')}
                        />
                      ) : (
                        <div className='bg-muted text-muted-foreground flex aspect-square items-center justify-center rounded-md'>
                          {t('No image data returned')}
                        </div>
                      )}
                      {image.revised_prompt && (
                        <p className='text-muted-foreground text-xs'>
                          {image.revised_prompt}
                        </p>
                      )}
                      {source && (
                        <Button
                          className='w-full'
                          variant='outline'
                          render={
                            <a href={source} target='_blank' rel='noreferrer' />
                          }
                        >
                          <ExternalLink />
                          {t('Open image')}
                        </Button>
                      )}
                    </div>
                  )
                })}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </Main>
  )
}
